# Compiled with 0.50.0 rules

# Don't add any files/directories to the 'include:' section. Everything not
# listed under 'excluded:' should be linted.

excluded: # paths to ignore during linting. Takes precedence over `included`.
# Third-party directories

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)

## Rules

# enabled_rules (for documentation):
#  - compiler_protocol_init
#  - closing_brace
#  - colon
#  - comma
#  - comment_spacing
#  - computed_accessors_order
#  - control_statement
#  - discarded_notification_center_observer
#  - empty_enum_arguments
#  - force_cast
#  - force_try
#  - implicit_getter
#  - leading_whitespace
#  - legacy_constructor
#  - large_tuple
#  - mark
#  - notification_center_detachment
#  - opening_brace
#  - operator_whitespace
#  - orphaned_doc_comment
#  - redundant_objc_attribute
#  - redundant_optional_initialization
#  - redundant_void_return
#  - statement_position
#  - switch_case_alignment
#  - syntactic_sugar
#  - trailing_comma
#  - trailing_newline
#  - trailing_semicolon
#  - unused_closure_parameter
#  - unused_optional_binding
#  - unused_setter_value
#  - vertical_whitespace
#  - weak_delegate

opt_in_rules:
- explicit_init
- overridden_super_call
- operator_usage_whitespace
- conditional_returns_on_newline
- orphaned_doc_comment

disabled_rules:
- shorthand_operator
- class_delegate_protocol
- function_parameter_count
- for_where
- function_body_length
- identifier_name
- line_length
- multiple_closures_with_trailing_closure
- nesting
- opening_brace
- private_over_fileprivate
- todo
- trailing_whitespace
- type_name
- void_function_in_ternary
- void_return
- cyclomatic_complexity
- switch_case_alignment

## Rule Configuration
trailing_comma:
 mandatory_comma: true
